# Generated by Django 2.2.19 on 2021-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('email', models.TextField()),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer', models.TextField()),
                ('comment', models.TextField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReportStudent',
        ),
        migrations.DeleteModel(
            name='ReportTeacher',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='onlinetest',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='pub_test',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='question',
            field=models.ManyToManyField(to='server.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='onlinetest',
            name='headline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='user_answer',
            field=models.ManyToManyField(to='server.UserAnswer'),
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='users',
            field=models.ManyToManyField(to='server.User'),
        ),
    ]
