# Generated by Django 2.2.19 on 2021-03-23 11:35

from django.db import migrations, models
import djongo.models.fields
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210320_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetest',
            name='creator',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='onlinetest',
            name='question',
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='question',
            field=djongo.models.fields.EmbeddedField(model_container=server.models.Question, null=True),
        ),
        migrations.RemoveField(
            model_name='onlinetest',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='user_answer',
            field=djongo.models.fields.EmbeddedField(model_container=server.models.UserAnswer, null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
