# Generated by Django 2.2.19 on 2021-03-25 21:44

from django.db import migrations, models
import djongo.models.fields
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210323_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmailaddress',
            fields=[
                ('email', models.CharField(max_length=50, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('primary', models.BooleanField()),
                ('user_id', models.IntegerField()),
                ('verified', models.BooleanField()),
            ],
            options={
                'db_table': 'account_emailaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmailconfirmation',
            fields=[
                ('created', models.DateTimeField()),
                ('email_address_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('sent', models.DateTimeField()),
            ],
            options={
                'db_table': 'account_emailconfirmation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('group_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('codename', models.CharField(max_length=50)),
                ('content_type_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField()),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('group_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('action_flag', models.IntegerField()),
                ('action_time', models.DateTimeField()),
                ('change_message', models.CharField(max_length=50)),
                ('content_type_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('app_label', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('app', models.CharField(max_length=50)),
                ('applied', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('expire_date', models.DateTimeField()),
                ('session_data', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('domain', models.CharField(max_length=50, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerOnlinetest',
            fields=[
                ('headline', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'server_onlinetest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerOnlinetestUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('onlinetest_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'server_onlinetest_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('birth_date', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'server_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialaccount',
            fields=[
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField()),
                ('provider', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialapp',
            fields=[
                ('client_id', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'socialaccount_socialapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialappSites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField()),
                ('socialapp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'socialaccount_socialapp_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialtoken',
            fields=[
                ('account_id', models.IntegerField()),
                ('app_id', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('token_secret', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'socialaccount_socialtoken',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='onlinetest',
            name='users',
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='users',
            field=djongo.models.fields.ArrayField(model_container=server.models.AuthUser, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
