# Generated by Django 2.2.19 on 2021-03-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210325_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineTest',
        ),
    ]
