# Generated by Django 2.2.19 on 2021-03-25 21:48

from django.db import migrations, models
import djongo.models.fields
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_delete_onlinetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('pub_test', models.DateField(null=True)),
                ('creator', models.IntegerField(null=True)),
                ('users', djongo.models.fields.ArrayField(model_container=server.models.AuthUser, null=True)),
                ('question', djongo.models.fields.EmbeddedField(model_container=server.models.Question, null=True)),
                ('user_answer', djongo.models.fields.EmbeddedField(model_container=server.models.UserAnswer, null=True)),
            ],
        ),
    ]
