# Generated by Django 2.2.19 on 2021-03-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_onlinetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinetest',
            name='users',
        ),
    ]
