# Generated by Django 2.2.19 on 2021-03-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_onlinetest_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountEmailaddress',
        ),
        migrations.DeleteModel(
            name='AccountEmailconfirmation',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialaccount',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialapp',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialappSites',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialtoken',
        ),
    ]
