# Generated by Django 2.2.19 on 2021-03-25 22:44

from django.db import migrations
import djongo.models.fields
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_remove_onlinetest_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetest',
            name='users',
            field=djongo.models.fields.ArrayField(model_container=server.models.AuthUser, null=True),
        ),
    ]
