# Generated by Django 2.2.19 on 2021-03-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20210330_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_permission',
        ),
    ]
