# Generated by Django 2.2.19 on 2021-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_delete_auth_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('codename', models.CharField(max_length=50)),
                ('content_type_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
    ]
